data:
  name: airplane_bg
  sub_dirs: ['airplane1_bg0']
  nlabels: 1
  impath: '/home/youssef/Documents/phdYoop/datasets/airplane/beauty/PNG'
generator:
  render_type: point
  bg_cube: False
training:
  batch_size: 16
  out_dir: results/airplane
