data:
  name: beehover_bg
  sub_dirs: ['beehover1_bg0']
  nlabels: 1
  impath: '/home/youssef/Documents/phdYoop/datasets/beehover/beauty/PNG'
generator:
  render_type: point
  bg_cube: False
training:
  batch_size: 16
  out_dir: results/beehover
